version: '3'

services: 
  app: 
    container_name: tyba-challenge
    restart: always
    build: .
    ports:
      - "3000:3000"
    links: 
      - db
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
